### ISSUE TITLE
Botched Break Dialog

### ISSUE THREAD

**Issue by tametsi** [johndoe31415/pyradium#63]
Hi, it's me again with some issues regarding the premium design one is faced with when using pyradium :upside_down_face:.

The nice background shadow on the dialog that opens when a break is started seems to have a vertical gap on the left side of the presentation. This is misleading to anyone looking at the presentation during pauses and needs to be fixed immediately.

Fixing this is as simple as removing the default padding that the lovely browser sets by default for `body` and adding the 10px margin back to the slide's `.size_container`. However, a future-proof approach might be to use the [html dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). What do you think about this?

**Comment by johndoe31415** [comment]
OMG I am shocked and humbled such a critical oversight and functioanlity-breaking bug ever made it into production.

I am unfamiliar with `<dialog>` but am willing to accept a reasonable PR that ends this awful bug once and for all. I will make this my absolutely TOP priority.

After the issue is fixed there needs to be a thorough post-mortem to analyze in detail how such a cataclysmic event was ever possible and what we -- humanity as a whole -- can do to ever prevent such terrible tragedy in the future. May we push back the unsightly margin in the pits of hell so it can find its final resting place.

**Comment by tametsi** [comment]
Alright, sounds reasonable. I'll take a look at it when I find some time between classes...

As for the analysis, I might be able to provide important information extracted from git blame :). Just let me know if that could help.
